Hospitales/Models/TipoUsuario.cs
using System;
using System.Collections.Generic;

namespace Hospitales.Models
{
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            TipoUsuarioPaginas = new HashSet<TipoUsuarioPagina>();
            Usuarios = new HashSet<Usuario>();
        }

        public int Iidtipousuario { get; set; }
        public string? Nombre { get; set; }
        public string? Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<TipoUsuarioPagina> TipoUsuarioPaginas { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}

Hospitales/Controllers/TipoUsuarioController.cs
using Hospitales.Clases;
using Hospitales.Filters;
using Hospitales.Helpers;
using Hospitales.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;

namespace Hospitales.Controllers
{
    [ServiceFilter(typeof(Seguridad))]
    public class TipoUsuarioController : Controller
    {
        private readonly BDHospitalContext context;

        public TipoUsuarioController(BDHospitalContext context)
        {
            this.context = context;
        }

        public async Task<IActionResult> Index(TipoUsuarioCLS otipoUsuarioCLS)
        {
            string controlador = ControllerContext.ActionDescriptor.ControllerName;
            List<PaginaCLS> listaBotonesPag = Listas.listarBotones(controlador);
            ViewBag.Botones = listaBotonesPag.Select(x => x.iidBoton).ToList();

            List<TipoUsuarioCLS> list = new List<TipoUsuarioCLS>();

            list = await (from usuario in context.TipoUsuarios
                          where usuario.Bhabilitado == 1
                          select new TipoUsuarioCLS()
                          {
                              Iidtipousuario = usuario.Iidtipousuario,
                              Nombre = usuario.Nombre,
                              Descripcion = usuario.Descripcion

                          }).ToListAsync();

            if (otipoUsuarioCLS.Iidtipousuario == 0 && otipoUsuarioCLS.Nombre == null && otipoUsuarioCLS.Descripcion == null)
            {
                ViewBag.Iidtipousuario = 0;
                ViewBag.Nombre = "";
                ViewBag.Descripcion = "";
            }
            else
            {
                if (otipoUsuarioCLS.Iidtipousuario != 0)
                {
                    list = list.Where(x => x.Iidtipousuario == otipoUsuarioCLS.Iidtipousuario).ToList();
                }
                if (otipoUsuarioCLS.Nombre != null)
                {
                    list = list.Where(x => x.Nombre.Contains(otipoUsuarioCLS.Nombre)).ToList();
                }
                if (otipoUsuarioCLS.Descripcion != null)
                {
                    list = list.Where(x => x.Descripcion.Contains(otipoUsuarioCLS.Descripcion)).ToList();
                }

                ViewBag.Iidtipousuario = otipoUsuarioCLS.Iidtipousuario;
                ViewBag.Nombre = otipoUsuarioCLS.Nombre;
                ViewBag.Descripcion = otipoUsuarioCLS.Descripcion;
            }


            return View(list);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<string> Guardar(TipoUsuarioCLS oTipoUsuarioCLS, int[] idPaginas, int[] idVistas)
        {
            string nombreVista = oTipoUsuarioCLS.Iidtipousuario == 0 ? "Create" : "Edit";
            bool existeNombre = false;
            bool existeDescripcion = false;
            string resp = "";

            try
            {
                using (var trasnsaccion = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
                {

                    if (oTipoUsuarioCLS.Iidtipousuario == 0 && ModelState.IsValid)
                    {
                        existeNombre = await context.TipoUsuarios.AnyAsync(x => x.Nombre.Trim().ToUpper() == oTipoUsuarioCLS.Nombre.Trim().ToUpper());
                        existeDescripcion = await context.TipoUsuarios.AnyAsync(x => x.Descripcion.Trim().ToUpper() == oTipoUsuarioCLS.Descripcion.Trim().ToUpper());
                    }
                    else if (oTipoUsuarioCLS.Iidtipousuario != 0 && ModelState.IsValid)
                    {
                        existeNombre = await context.TipoUsuarios.AnyAsync(x => x.Nombre.Trim().ToUpper() == oTipoUsuarioCLS.Nombre.Trim().ToUpper() && x.Iidtipousuario != oTipoUsuarioCLS.Iidtipousuario);
                        existeDescripcion = await context.TipoUsuarios.AnyAsync(x => x.Descripcion.Trim().ToUpper() == oTipoUsuarioCLS.Descripcion.Trim().ToUpper() && x.Iidtipousuario != oTipoUsuarioCLS.Iidtipousuario);
                    }

                    if (!ModelState.IsValid || existeNombre || existeDescripcion)
                    {
                        var errores = (from state in ModelState.Values
                                       from error in state.Errors
                                       select error.ErrorMessage).ToList();

                        resp += "<ul class = 'list-group'>";

                        if (existeNombre) resp += "<li class = 'list-group-item text-danger'>Ya existe en la BD ese Tipo de Usuario..</li>";
                        if (existeDescripcion) resp += "<li class = 'list-group-item text-danger'>Ya existe esa misma descripción en la BD..</li>";

                        foreach (var item in errores)
                        {
                            resp += $"<li class = 'list-group-item text-danger'>{item}</li>";
                        }
                        resp += "</ul>";
                    }
                    else
                    {
                        if (oTipoUsuarioCLS.Iidtipousuario == 0)
                        {
                            TipoUsuario tipoUsuario = new TipoUsuario();

                            tipoUsuario.Nombre = oTipoUsuarioCLS.Nombre;
                            tipoUsuario.Descripcion = oTipoUsuarioCLS.Descripcion;
                            tipoUsuario.Bhabilitado = 1;

                            context.TipoUsuarios.Add(tipoUsuario);
                            await context.SaveChangesAsync();

                            trasnsaccion.Complete();

                            resp = "1";

                        }
                        else
                        {
                            TipoUsuario tipoUsuario = await context.TipoUsuarios.FirstOrDefaultAsync(x => x.Iidtipousuario == oTipoUsuarioCLS.Iidtipousuario);

                            tipoUsuario.Nombre = oTipoUsuarioCLS.Nombre;
                            tipoUsuario.Descripcion = oTipoUsuarioCLS.Descripcion;

                            List<TipoUsuarioPagina> list = await context.TipoUsuarioPaginas.Where(x => x.Iidtipousuario == oTipoUsuarioCLS.Iidtipousuario).ToListAsync();

                            if (list != null)
                            {
                                foreach (var item in list)
                                {
                                    item.Bhabilitado = 0;
                                }
                            }

                            int indice = 0;

                            foreach (var item in idPaginas)
                            {
                                var existe = await context.TipoUsuarioPaginas.AnyAsync(x => x.Iidtipousuario == oTipoUsuarioCLS.Iidtipousuario && x.Iidpagina == item);
                                if (!existe)
                                {
                                    TipoUsuarioPagina tipoUsuarioPagina = new TipoUsuarioPagina();

                                    tipoUsuarioPagina.Iidtipousuario = oTipoUsuarioCLS.Iidtipousuario;
                                    tipoUsuarioPagina.Iidpagina = item;
                                    tipoUsuarioPagina.Iidvista = idVistas[indice];
                                    tipoUsuarioPagina.Bhabilitado = 1;

                                    context.TipoUsuarioPaginas.Add(tipoUsuarioPagina);
                                }
                                else
                                {
                                    TipoUsuarioPagina tipoUsuarioPagina = await context.TipoUsuarioPaginas.FirstOrDefaultAsync(x => x.Iidtipousuario == oTipoUsuarioCLS.Iidtipousuario && x.Iidpagina == item);
                                    tipoUsuarioPagina.Iidvista = idVistas[indice];
                                    tipoUsuarioPagina.Bhabilitado = 1;
                                }
                                indice ++;  
                            }

                            await context.SaveChangesAsync();

                            trasnsaccion.Complete();

                            resp = "1";
                        }

                    }
                }

            }
            catch (Exception ex)
            {
                return resp;
            }

            return resp;
        }

        public async Task<IActionResult> Edit(int id)
        {
            TipoUsuarioCLS tipoUsuarioCLS = new TipoUsuarioCLS();
            TipoUsuario tipoUsuario = await context.TipoUsuarios.FirstOrDefaultAsync(x => x.Iidtipousuario == id);

            tipoUsuarioCLS.Iidtipousuario = tipoUsuario.Iidtipousuario;
            tipoUsuarioCLS.Nombre = tipoUsuario.Nombre;
            tipoUsuarioCLS.Descripcion = tipoUsuario.Descripcion;

            return View(tipoUsuarioCLS);
        }

        public async Task<List<PaginaCLS>> ObtenerPaginas(int id)
        {
            List<PaginaCLS> list = await (from tipoUsuarioPag in context.TipoUsuarioPaginas
                                          where tipoUsuarioPag.Bhabilitado == 1 && tipoUsuarioPag.Iidtipousuario == id
                                          select new PaginaCLS()
                                          {
                                              Iidpagina = (int)tipoUsuarioPag.Iidpagina,
                                              iidVista = tipoUsuarioPag.Iidvista == null ? 0 : (int)tipoUsuarioPag.Iidvista

                                          }).ToListAsync();

            return list;
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int idEliminar)
        {
            try
            {
                TipoUsuario tipoUsuario = await context.TipoUsuarios.FirstAsync(x => x.Iidtipousuario == idEliminar);

                context.TipoUsuarios.Remove(tipoUsuario);

Hospitales/Views/TipoUsuario/Create.cshtml
@model Hospitales.Clases.TipoUsuarioCLS

@{
    ViewData["Title"] = "Tipos Usuario";
}

<h1>Create</h1>
<hr />
<div class="row">
    <div class="col-md-6">
            <div class="form-group">
                <label class="control-label">Nombre</label>
                <input id ="Nombre" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Descripción</label>
                <input id = "Descripcion" class="form-control" />
            </div>
            <div class="form-group d-flex justify-content-between align-items-center mt-4">
                <a asp-action="Index" asp-controller="TipoUsuario" class="btn btn-secondary">Cancelar</a>
                <input type="button" value="Aceptar" class="btn btn-primary" onclick="Enviar()" />
            </div>
            <div id="divErrores"></div>
    </div>
</div>

@section Scripts{
    <script>
        function Enviar() {
            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    Guardar();
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }

        function Guardar() {
            let Nombre = document.getElementById("Nombre").value;
            let Descripcion = document.getElementById("Descripcion").value;

            let frm = new FormData();
            frm.append("Nombre", Nombre);
            frm.append("Descripcion", Descripcion);

            $.ajax({
                type: "POST",
                url: "/TipoUsuario/Guardar",
                data: frm,
                processData: false,
                contentType : false,
                success: (resp) => {
                    if (resp == "1") {
                        exito("Guardado correctamente..");
                        window.location = "/TipoUsuario/Index";
                    }
                    else {
                        error();
                        document.getElementById("divErrores").innerHTML = resp;
                    }
                }
            });
        }
    </script>
}

Hospitales/Views/TipoUsuario/Edit.cshtml
@model Hospitales.Clases.TipoUsuarioCLS

@{
    ViewData["Title"] = "Tipos Usuario";
}

<h1>Edit</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <input type="hidden" asp-for="Iidtipousuario" id="Iidtipousuario" />
        <div class="form-group">
            <label asp-for="Nombre" class="control-label"></label>
            <input asp-for="Nombre" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Descripcion" class="control-label"></label>
            <input asp-for="Descripcion" class="form-control" />
        </div>
        <div id="divErrores"></div>
        <div id="divPaginas"></div>
        <div class="form-group d-flex justify-content-between align-items-center mt-4">
            <a asp-action="Index" asp-controller="TipoUsuario" class="btn btn-secondary">Cancelar</a>
            <input type="button" value="Aceptar" class="btn btn-primary" onclick="Enviar()" />
        </div>
    </div>
</div>

@section Scripts{
    <script>

        window.onload = () => {
            listarPaginas();
        }

        function listarPaginas() {
            let contenido = "";

            $.get("/Pagina/listar", (resp) => {
                if (resp != null) {
                    contenido += "<table class = 'table table-striped'>";
                    contenido += "<thead>";
                    contenido += "<tr>";
                    contenido += "<th>Mensaje</th><th>Accion</th><th>Controlador</th><th>Tipo Vista</th><th></th>";
                    contenido += "</tr>";
                    contenido += "</thead>";
                    contenido += "<tbody>";
                    resp.forEach((item) => {
                        contenido += "<tr>";
                        contenido += `<td>${item.mensaje}</td><td>${item.accion}</td><td>${item.controlador}</td><td><select id = 'cbo${item.iidpagina}'><option value = '0'>Selecciona..</option><option value = '1'>Vista Total</option><option value = '2'>Vista Parcial</option></select></td><td><input type='checkbox' class = 'check' id = 'chk${item.iidpagina}' /></td>`;
                        contenido += "</tr>";
                    });
                    contenido += "</tbody>";
                    contenido += "</table>";

                    document.getElementById("divPaginas").innerHTML = contenido;

                    ObtenerPaginas();
                }
            });
        }

        function Enviar() {
            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    Guardar();
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }

        function Guardar() {
            let Iidtipousuario = document.getElementById("Iidtipousuario").value;
            let Nombre = document.getElementById("Nombre").value;
            let Descripcion = document.getElementById("Descripcion").value;
            let checks = document.getElementsByClassName("check");

            let frm = new FormData();
            frm.append("Iidtipousuario", Iidtipousuario);
            frm.append("Nombre", Nombre);
            frm.append("Descripcion", Descripcion);

            Array.from(checks).forEach(item => {
                if (item.checked == true) {
                    let iidpagina = item.id.replace("chk", "") * 1;
                    frm.append("idPaginas[]", iidpagina);
                    let cbo = document.getElementById("cbo" + iidpagina).value;
                    frm.append("idVistas[]", cbo * 1);
                }
            });

            $.ajax({
                type: "POST",
                url: "/TipoUsuario/Guardar",
                data: frm,
                processData: false,
                contentType: false,
                success: (resp) => {
                    if (resp == "1") {
                        window.location = "/TipoUsuario/Index";
                        exito("Guardado correctamente..");
                    }
                    else {
                        error();
                        document.getElementById("divErrores").innerHTML = resp;
                    }
                }
            });
        }

        function ObtenerPaginas() {
            let id = document.getElementById("Iidtipousuario").value;

            $.get("/TipoUsuario/ObtenerPaginas/?id=" + id, (resp) => {
                console.table(resp);
                resp.forEach(item => {
                    let idcheck = "chk"+item.iidpagina;
                    document.getElementById(idcheck).checked = true;
                    document.getElementById("cbo"+item.iidpagina).value = item.iidVista;
                });
            });
        }

    </script>
}

Hospitales/Views/TipoUsuario/Index.cshtml
@model IEnumerable<Hospitales.Clases.TipoUsuarioCLS>

@{
    ViewData["Title"] = "Tipos Usuario";
}

<h1>Tipos Usuario</h1>
<hr />

<form asp-controller="TipoUsuario" asp-action="Index">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <a asp-action="Create" asp-controller="TipoUsuario" class="btn btn-primary">Nuevo</a>
        <input type="submit" value="Buscar" class="btn btn-info mb-2" />
    </div>
    
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Iidtipousuario)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Descripcion)
                </th>
                <th></th>
            </tr>

            <tr>
                <th>
                    @if(ViewBag.Iidtipousuario == 0)
                    {
                        <input type="number" name="Iidtipousuario" class="from form-control" placeholder="Id.." />
                    }
                    else
                    {
                        <input type="number" name="Iidtipousuario" class="from form-control" value="@ViewBag.Iidtipousuario" placeholder="Id.." />
                    }
                </th>
                <th>
                    <input type="text" name="Nombre" class="from form-control" value="@ViewBag.Nombre" placeholder="Nombre.." />
                </th>
                <th>
                    <input type="text" name="Descripcion" class="from form-control" value="@ViewBag.Descripcion" placeholder="Descripción.." />
                </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Iidtipousuario)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nombre)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Descripcion)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-asp-controller="TipoUsuario" asp-route-id="@item.Iidtipousuario"><i class="fa fa-pencil-square-o text-primary me-4" aria-hidden="true"></i></a>
                        <span onclick="Eliminar(@item.Iidtipousuario)"><i class="fa fa-trash-o text-danger" aria-hidden="true"></i></span>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>

<form asp-action="Delete" asp-controller="TipoUsuario" method="post" id="frmDelete">
    <input type="hidden" id="txtDelete" name="idEliminar" />
</form>

@section Scripts{
    <script>

        function Eliminar(id) {
            document.getElementById("txtDelete").value = id;

            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    document.getElementById("frmDelete").submit();
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }

    </script>
}