Hospitales/Models/Medicamento.cs
using System;
using System.Collections.Generic;

namespace Hospitales.Models
{
    public partial class Medicamento
    {
        public Medicamento()
        {
            CitaMedicamentos = new HashSet<CitaMedicamento>();
        }

        public int Iidmedicamento { get; set; }
        public string? Nombre { get; set; }
        public string? Concentracion { get; set; }
        public int? Iidformafarmaceutica { get; set; }
        public decimal? Precio { get; set; }
        public int? Stock { get; set; }
        public string? Presentacion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual FormaFarmaceutica? IidformafarmaceuticaNavigation { get; set; }
        public virtual ICollection<CitaMedicamento> CitaMedicamentos { get; set; }
    }
}

Hospitales/Controllers/MedicamentoController.cs
using Hospitales.Clases;
using Hospitales.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Linq;
using Hospitales.Helpers;
using Hospitales.Filters;

namespace Hospitales.Controllers
{
    [ServiceFilter(typeof(Seguridad))]
    public class MedicamentoController : Controller
    {
        private readonly BDHospitalContext context;
        private readonly IReporting reporting;
        private static List<MedicamentoCLS> listaMedicamentos;

        public MedicamentoController(BDHospitalContext context, IReporting reporting)
        {
            this.context = context;
            this.reporting = reporting;
        }


        public async Task<IActionResult> Index()
        {
            string controlador = ControllerContext.ActionDescriptor.ControllerName;
            List<PaginaCLS> listaBotonesPag = Listas.listarBotones(controlador);
            ViewBag.Botones = listaBotonesPag.Select(x => x.iidBoton).ToList();

            await LlenarFormaFarmac();
            return View();
        }

        public async Task<List<MedicamentoCLS>> Listar(int IidFF)
        {
            await LlenarFormaFarmac();

            List<MedicamentoCLS> list = new List<MedicamentoCLS>();

            if (IidFF == 0)
            {
                list = await (from medicamento in context.Medicamentos
                              join formaFarmaceutica in context.FormaFarmaceuticas
                              on medicamento.Iidformafarmaceutica equals formaFarmaceutica.Iidformafarmaceutica
                              where medicamento.Bhabilitado == 1
                              select new MedicamentoCLS()
                              {
                                  Iidmedicamento = medicamento.Iidmedicamento,
                                  Nombre = medicamento.Nombre,
                                  Precio = medicamento.Precio,
                                  Stock = (int)medicamento.Stock,
                                  NombreFormaFarmaceutica = formaFarmaceutica.Nombre

                              }).ToListAsync();

                listaMedicamentos = list;
            }
            else
            {
                list = await (from medicamento in context.Medicamentos
                              join formaFarmaceutica in context.FormaFarmaceuticas
                              on medicamento.Iidformafarmaceutica equals formaFarmaceutica.Iidformafarmaceutica
                              where medicamento.Bhabilitado == 1 && medicamento.Iidformafarmaceutica == IidFF
                              select new MedicamentoCLS()
                              {
                                  Iidmedicamento = medicamento.Iidmedicamento,
                                  Nombre = medicamento.Nombre,
                                  Precio = medicamento.Precio,
                                  Stock = (int)medicamento.Stock,
                                  NombreFormaFarmaceutica = formaFarmaceutica.Nombre

                              }).ToListAsync();

                listaMedicamentos = list;
            }

            return list;
        }

        public async Task<IActionResult> Create()
        {
            await LlenarFormaFarmac();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Guardar(MedicamentoCLS oMedicamentoCLS)
        {
            string nombreVista = oMedicamentoCLS.Iidmedicamento == 0 ? "Create" : "Edit";
            try
            {
                if (!ModelState.IsValid)
                {
                    await LlenarFormaFarmac();
                    return View(nombreVista, oMedicamentoCLS);
                }
                else
                {
                    if (oMedicamentoCLS.Iidmedicamento == 0)
                    {
                        Medicamento medicamento = new Medicamento();

                        medicamento.Nombre = oMedicamentoCLS.Nombre;
                        medicamento.Concentracion = oMedicamentoCLS.Concentracion;
                        medicamento.Precio = oMedicamentoCLS.Precio;
                        medicamento.Stock = oMedicamentoCLS.Stock;
                        medicamento.Presentacion = oMedicamentoCLS.Presentacion;
                        medicamento.Iidformafarmaceutica = oMedicamentoCLS.IidFormaFarmaceutica;
                        medicamento.Bhabilitado = 1;

                        context.Medicamentos.Add(medicamento);

                        await context.SaveChangesAsync();
                    }
                    else
                    {
                        Medicamento medicamento = await context.Medicamentos.FirstAsync(x => x.Iidmedicamento == oMedicamentoCLS.Iidmedicamento);

                        medicamento.Nombre = oMedicamentoCLS.Nombre;
                        medicamento.Concentracion = oMedicamentoCLS.Concentracion;
                        medicamento.Precio = oMedicamentoCLS.Precio;
                        medicamento.Stock = oMedicamentoCLS.Stock;
                        medicamento.Presentacion = oMedicamentoCLS.Presentacion;
                        medicamento.Iidformafarmaceutica = oMedicamentoCLS.IidFormaFarmaceutica;

                        await context.SaveChangesAsync();
                    }

                }
            }
            catch (Exception ex)
            {
                return View(nombreVista, oMedicamentoCLS);
            }

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            await LlenarFormaFarmac();

            MedicamentoCLS oMedicamentoCLS = new MedicamentoCLS();

            Medicamento medicamento = await context.Medicamentos.FirstAsync(x => x.Iidmedicamento == id);

            oMedicamentoCLS.Nombre = medicamento.Nombre;
            oMedicamentoCLS.Concentracion = medicamento.Concentracion;
            oMedicamentoCLS.Precio = medicamento.Precio;
            oMedicamentoCLS.Stock = (int)medicamento.Stock;
            oMedicamentoCLS.Presentacion = medicamento.Presentacion;
            oMedicamentoCLS.IidFormaFarmaceutica = medicamento.Iidformafarmaceutica;

            return View(oMedicamentoCLS);
        }

        [HttpPost]
        public async Task<int> Delete(int idEliminar)
        {
            int resp = 0;
            try
            {
                Medicamento medicamento = await context.Medicamentos.FirstAsync(x => x.Iidmedicamento == idEliminar);

                context.Medicamentos.Remove(medicamento);
                await context.SaveChangesAsync();

                resp = 1;
            }
            catch (Exception ex)
            {
                resp = 0;
            }

            return resp;
        }

        private async Task LlenarFormaFarmac()
        {
            List<SelectListItem> list = new List<SelectListItem>();

            list = await (from formaFarma in context.FormaFarmaceuticas
                          where formaFarma.Bhabilitado == 1
                          select new SelectListItem()
                          {
                              Text = formaFarma.Nombre,
                              Value = formaFarma.Iidformafarmaceutica.ToString()

                          }).ToListAsync();

            list.Insert(0, new SelectListItem()
            {
                Text = "Seleccione..",
                Value = ""
            });

            ViewBag.listaFF = list;
        }

        public FileResult Descargar(string[] nombrePropiedades, string tipo)
        {
            if (tipo == "excel")
            {
                byte[] file = reporting.Excel(listaMedicamentos, nombrePropiedades);

                return File(file, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
            }
            else if (tipo == "pdf")
            {
                byte[] file = reporting.Pdf("Medicamentos", nombrePropiedades, listaMedicamentos);
                return File(file, "application/pdf");
            }
            else if (tipo == "word")
            {
                byte[] file = reporting.Word("Medicamentos", nombrePropiedades, listaMedicamentos);
                return File(file, "application/vnd.openxmlformats-officedocument.wordprocessingml.document");
            }
            return null;
        }


        public string DescargarPDF(string[] nombrePropiedades)
        {
            byte[] file = reporting.Pdf("Medicamentos", nombrePropiedades, listaMedicamentos);
            string cadena = Convert.ToBase64String(file);
            cadena = "data:application/pdf;base64," + cadena;

            return cadena;
        }
    }
}

Hospitales/Views/Medicamento/Create.cshtml
@using Hospitales.Clases;
@model MedicamentoCLS
@{
    ViewData["Title"] = "Medicamentos";
    List<SelectListItem> listaFF = ViewBag.listaFF;
}

<h1>Create</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Guardar" asp-controller="Medicamento" method="post" id="frm">
            <div class="form-group">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" type="text" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Concentracion"></label>
                <input asp-for="Concentracion" type="text" class="form-control" />
                <span asp-validation-for="Concentracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio"></label>
                <input asp-for="Precio" type="number" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock"></label>
                <input asp-for="Stock" type="number" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presentacion"></label>
                <input asp-for="Presentacion" type="text" class="form-control" />
                <span asp-validation-for="Presentacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IidFormaFarmaceutica"></label>
                <select asp-for="IidFormaFarmaceutica" asp-items="listaFF" class="form-select"></select>
                <span asp-validation-for="IidFormaFarmaceutica" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between mt-4">
                <a asp-action="Index" asp-controller="Medicamento" class="btn btn-secondary">Cancelar</a>
                <input type="button" class="btn btn-primary" value="Aceptar" onclick="Enviar()" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        function Enviar() {
            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    document.getElementById("frm").submit();
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }
    </script>
}

Hospitales/Views/Medicamento/Edit.cshtml
@using Hospitales.Clases;
@model MedicamentoCLS
@{
    ViewData["Title"] = "Medicamentos";
    List<SelectListItem> listaFF = ViewBag.listaFF;
}

<h1>Edit</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Guardar" asp-controller="Medicamento" method="post" id="frm">
            <input type="hidden" asp-for="Iidmedicamento" />
            <div class="form-group">
                <label asp-for="Nombre"></label>
                <input asp-for="Nombre" type="text" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Concentracion"></label>
                <input asp-for="Concentracion" type="text" class="form-control" />
                <span asp-validation-for="Concentracion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Precio"></label>
                <input asp-for="Precio" type="number" class="form-control" />
                <span asp-validation-for="Precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock"></label>
                <input asp-for="Stock" type="number" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presentacion"></label>
                <input asp-for="Presentacion" type="text" class="form-control" />
                <span asp-validation-for="Presentacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IidFormaFarmaceutica"></label>
                <select asp-for="IidFormaFarmaceutica" asp-items="listaFF" class="form-select"></select>
                <span asp-validation-for="IidFormaFarmaceutica" class="text-danger"></span>
            </div>
            <div class="form-group d-flex justify-content-between mt-4">
                <a asp-action="Index" asp-controller="Medicamento" class="btn btn-secondary">Cancelar</a>
                <input type="button" class="btn btn-primary" value="Aceptar" onclick="Enviar()" />
            </div>
        </form>
    </div>
</div>

@section Scripts{
    <script>
        function Enviar() {
            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    document.getElementById("frm").submit();
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }
    </script>
}

Hospitales/Views/Medicamento/Index.cshtml
@model IEnumerable<Hospitales.Clases.MedicamentoCLS>

@{
    ViewData["Title"] = "Medicamentos";
    List<SelectListItem> listaFF = ViewBag.ListaFF;
    List<int> botones = ViewBag.Botones;
}

<h1>Medicamentos</h1>
<hr />
<div class="d-flex justify-content-between align-items-center mb-2">
    @if (botones != null && botones.Contains(1))
    {
        <div>
            <a asp-action="Create" asp-controller="Medicamento" class="btn btn-primary">Nuevo</a>
        </div>
    }
    <div class="w-25 d-flex align-items-center">
        <label class="me-4">Forma</label>
        @Html.DropDownList("IidFF", listaFF, new{ @class = "form-select"})
    </div>
    <div>
        @if (botones != null && botones.Contains(4))
        {
            <input type="button" value="Excel" class="btn btn-outline-success" onclick="Excel()" />
        }

        @if (botones != null && botones.Contains(5))
        {
            <input type="button" value="Word" class="btn btn-outline-primary ms-2" onclick="Word()" />
        }

        @if (botones != null && botones.Contains(6))
        {
            <input type="button" value="PDF" class="btn btn-outline-danger ms-2" onclick="PDF()" />
        }
        @if (botones != null && botones.Contains(7))
        {
            <input type="button" value="Imprimir" class="btn btn-outline-secondary ms-2" onclick="Imprimir('Medicamentos')" />
        }
        @if (botones != null && botones.Contains(1007))
        {
            <input type="button" value="Descargar" class="btn btn-outline-info ms-2" onclick="DescargarPDF('Medicamento','Medicamentos')" />
        }
    </div>
</div>

<form asp-action="Descargar" asp-controller="Medicamento" id="frmExportar">
    <table class="table table-striped" id="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Iidmedicamento)<input type="checkbox" class="ms-1 trCheck" checked name="nombrePropiedades" value="Iidmedicamento" />
                    <input type="hidden" name="tipo" id="tipo" />
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nombre)<input type="checkbox" class="ms-1 trCheck" checked name="nombrePropiedades" value="Nombre" />
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Precio)<input type="checkbox" class="ms-1 trCheck" checked name="nombrePropiedades" value="Precio" />
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Stock)<input type="checkbox" class="ms-1 trCheck" checked name="nombrePropiedades" value="Stock" />
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.NombreFormaFarmaceutica)<input type="checkbox" class="ms-1 trCheck" checked name="nombrePropiedades" value="NombreFormaFarmaceutica" />
                </th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody id="tbody">
        </tbody>
    </table>
</form>


<input type="hidden" id="txtDelete" name="idEliminar" />

@if (botones != null && botones.Contains(2))
{
    <input id="editar" type="hidden" value="1" />
}
else
{
    <input id="editar" type="hidden" value="0" />
}
@if (botones != null && botones.Contains(3))
{
    <input id="eliminar" type="hidden" value="1" />
}
else
{
    <input id="eliminar" type="hidden" value="0" />
}

@section Scripts{
    <script>

        document.getElementById("IidFF").onchange = function () {
            Buscar();
        }

        let controller = "Medicamento";
        let action = "Edit";
        let campos = ["iidmedicamento", "nombre", "precio", "stock", "nombreFormaFarmaceutica"];
        let editar = document.getElementById("editar").value;
        let eliminar = document.getElementById("eliminar").value;

        window.onload = () => {

            Listar();
        }

        function Listar() {
            let url = "/Medicamento/Listar";
            Tabla(url, campos, controller, false, editar, eliminar);
        }

        function Buscar() {

            let IidFF = document.getElementById("IidFF").value;
            let url = "/Medicamento/Listar/?IidFF=" + IidFF;

            Tabla(url, campos, controller, false, editar, eliminar);
        }

        function Eliminar(id) {
            document.getElementById("txtDelete").value = id;

            mostrarModal().then(result => {
                if (result.isConfirmed) {
                    $.post("/Medicamento/Delete", { idEliminar: id }, (resp) => {
                        if (resp == 1) {
                            exito("Borrado correctamente..");
                            Listar();
                        }
                        else {
                            error();
                        }
                    });
                } else if (result.isDenied) {
                    Swal.fire('Los cambios no se han guardado', '', 'info')
                }
            });
        }

    </script>
}